
apiVersion: v1
kind: Service
metadata:
  name: run
spec:
  selector:
    app: just 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080 

#kubectl apply -f service.yaml
