name: Dummy Notify Email Workflow

on:
  workflow_dispatch:

jobs:
  notify-only:
    runs-on: ubuntu-latest

    notify:
      email: anandb@aggregate,guruprakash@aggregate

    steps:
      - name: Just echo
        run: echo "This workflow only tests notify structure"
